Parameters: 
  BucketName: 
    Description: The name of the role that allows Automation to perform the actions on your behalf.
    Type: String
  
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub
        - "${AWS::Region}-${bucketname}"
        - bucketname: !Ref BucketName